### ISSUE TITLE
Documentation implies that you must always specify a location

### ISSUE THREAD

**Issue by arnaldop** [micronaut-projects/micronaut-flyway#30]
The guide (https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html) shows that this snippet is necessary:

```
flyway:
  datasources:
    default: 
      locations: classpath:databasemigrations
    books: 
      locations: classpath:databasemigrations
```

Nothing in the document indicates that this setting is optional. However, using it overrides Flyway's default location (`db/migration`).

After an hour stepping through the tests and Flyway code, I figured out that this is sufficient:

```
flyway:
  datasources:
    default:
      enabled: true
```

Not specifying the `flyway.datasources` property set skips the `FlywayConfigurationProperties` auto-configuration. The documentation is correct, in that, if you override the locations, the auto-configuration will be loaded with the defaults, but then you lose the default location provided by Flyway itself.

I suggest that the primary snippet be changed to only contain an `enabled` property. Then, below that, another example can show the multiple locations scenario. This will illustrate to new users that simply "enabling" the micronaut-flyway library will already yield its full benefits, and then, separately, it will indicate that some customization is also possible.

An example of these properties at work can be found here: https://github.com/arnaldop/flyway-default-location
