### ISSUE TITLE
Configure a baseline version

### ISSUE THREAD

**Issue by aiescola** [micronaut-projects/micronaut-flyway#417]
### Issue description

I have a project that has a lof of migrations (currently we are at `V0175__foo.sql`)

I want to use a baseline migration as stated here: [baseline migrations](https://flywaydb.org/documentation/concepts/baselinemigrations.html) and here [tutorial](https://flywaydb.org/documentation/tutorials/baselineMigrations). That is to say, I would like to have a B0175__Baseline.sql that will be the only script that will be run when I start a new container.

My question is that this feature is marked as a Flyway Teams, but the micronaut-flyway library has flags for it: https://micronaut-projects.github.io/micronaut-flyway/latest/guide/#additionalConfig

```
flyway.datasources.*.baseline-version 
flyway.datasources.*.baseline-description 
flyway.datasources.*.baseline-on-migrate 
flyway.datasources.*.baseline-migration-prefix
```

But as much as I've experimented I can't make it work.

This are the steps I'm following:
1º Run the application and execute the 175 migrations
2º Dump into a script the final state of the database and name it B0175_Baseline.sql.
3º Add this values to application.yml:
```
flyway:
  datasources:
    default:
      enabled: true
      baselineMigrationPrefix: B
      baselineVersion: 175
      baselineDescription: Baseline
      locations:
        - classpath:db/changelog/sql/migration
        - classpath:db/changelog/sql/data
```

Nothing happens. The script is ignored. What is the supposed procedure and behavior of the properties?

I may be doing something wrong as I haven't found an example.

Thanks in advance.
