### ISSUE TITLE
Allow Custom Properties to be set

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-flyway#442]
### Feature description

```
flyway:
  datasources:
    default:
      enabled: true
      username: ${datasource.username}
      password: ${datasource.password}
      url: ${datasource.url}
      driver: ${datasource.driver}
      properties:
         key1: value1
         key2: value2
```

Example

```
flyway:
  datasources:
    default:
      properties:
        flyway.postgresql.transactional.lock: false
```

Because of executing `CREATE INDEX CONCURRENTLY` inside Flyway's default Transaction.
This could be solved by calling `FluentConfiguration.configuration("postgresql.transactional.lock", "false")` in `FlywayMigrationFactory` before instantiating `Flyway`
