### ISSUE TITLE
Flyway migration before validation

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-flyway#7]
Currently the Hibernate Schema validation is done before database migration. Is it possible to do the flyway migration at first and then do the schema validation?

**Comment by saw303** [comment]
Just noticed this too. When using Flyway to migrate databases its very handy to use Hibernate schema validator to validate the schema **after** the migration.

Therefore it would be great if this configuration would work without having Hibernate complaining about schema validation issues.

```
jpa:
  default:
    packages-to-scan:
      - 'a.b.c'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false
flyway:
  datasources:
    default:
      locations: classpath:db/migration/mariadb
```
