### ISSUE TITLE
it it not work with hibernate-gorm

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-flyway#8]
my config like this

```
hibernate:
  hbm2ddl:
    auto: update
  show_sql: true
#  dbCreate: create-drop
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL57Dialect
    url: jdbc:mysql://127.0.0.1:3306/micronaut_test
    username: root
    password: root@123

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
```
